### ISSUE TITLE
Using .Net Core DLLs as fixtures

### ISSUE THREAD

**Issue by capstonecinc** [jediwhale/fitsharp#153]
When trying to use .net core dll's in a fixture I get the following error when running my tests. I've tried the workaround listed for the .net standard issue but no dice.  Is .net core in your roadmap? Is there another workaround try?

Thank you,

-Jamie

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at fitSharp.Machine.Engine.CurrentDomain.LoadAssembly(String assemblyPath)
   at fitSharp.Machine.Engine.ApplicationUnderTest.Assemblies.AddAssembly(String assemblyName)
   at fitSharp.Machine.Engine.ApplicationUnderTest.AddAssembly(String assemblyName)
   --- End of inner exception stack trace ---
   at fitSharp.Machine.Model.TypedValue.ThrowExceptionIfNotValid()
   at fitSharp.Machine.Application.SuiteConfiguration.LoadNode(String typeName, XmlNode methodNode)
   at fitSharp.Machine.Application.SuiteConfiguration.LoadXml(String configurationXml)
   at fitSharp.Machine.Application.ShellArguments.<>c__DisplayClass5_0.<LoadMemory>b__1(String value)
   at fitSharp.Machine.Application.ArgumentParser.InvokeArgumentHandler(String switch, String argumentValue)
   at fitSharp.Machine.Application.ArgumentParser.Parse(IList`1 commandLineArguments)
   at fitSharp.Machine.Application.ShellArguments.LoadMemory()
   at fitSharp.Machine.Application.Shell.Run()

**Comment by capstonecinc** [comment]
In the interim, I've cloned the source and now have it working with dotnet core.

**Comment by jediwhale** [comment]
I'm working on a .net core version.  Probably will be a couple of months.

**Comment by jediwhale** [comment]
That's good news.  Looks like it will be easier than I thought.

**Comment by capstonecinc** [comment]
I've commented out some of the missing pieces, as they are not needed for my usage.  But the Runner, fit, and fitSharp are very easy to get working.  Appreciate the work you've put into this.  Thank you.

**Comment by CumpsD** [comment]
@jediwhale out of curiosity, does this support .net core right now?

**Comment by jediwhale** [comment]
.net core 2.0 is now supported
