### ISSUE TITLE
Support for autocommit option

### ISSUE THREAD

**Issue by vladg0** [jediwhale/fitsharp#155]
I am running dbfit 3.2.0 with fitSharp 2.7.0 against SAP ASE 15.7

I am getting an error while trying to use !|set option|autocommit|true|

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ApplicationException: Unsupported optionautocommit
   at dbfit.util.Options.SetOption(CellProcessor processor, String name, String value)
   at dbfit.DatabaseTest.SetOption(String option, String value)

This indeed appears to be an unsupported option based on the latest code:
https://github.com/jediwhale/fitsharp/blob/master/source/dbfit/util/Options.cs

Without this feature,  I am unable to test any stored procedures that utilize temporary tables and other ddl operations that don't support nested transactions.

Thank you

**Comment by jediwhale** [comment]
fitSharp includes an older version of dbfit, implemented in .NET.  The Java version (http://dbfit.github.io/dbfit/) has had several enhancements that aren't in the .NET version.  I don't have the time or expertise at this point to add these enhancements to the .NET version so I have to rely on contributions from others for dbfit.
